import type { ProductType } from "@/(FSD)/shareds/types/product/Product.type";

export const productRankList: ProductType[] = [
    {
        productColorId: 1,
        name: "화이트 기본 반팔 티셔츠",
        brandName: "유니클로",
        price: 15000,
        sale: true,
        priceSale: 10,
        productState: "판매중",
        productImage: null,
        category: "상의",
        categorySub: "반팔",
        like: true,
    },
    {
        productColorId: 2,
        name: "블랙 긴팔 티셔츠",
        brandName: "지오다노",
        price: 20000,
        sale: false,
        priceSale: 0,
        productState: "판매중",
        productImage: null,
        category: "상의",
        categorySub: "긴팔",
        like: false,
    },
    {
        productColorId: 3,
        name: "빈티지 청바지",
        brandName: "리바이스",
        price: 50000,
        sale: true,
        priceSale: 15,
        productState: "판매중",
        productImage: null,
        category: "하의",
        categorySub: "청바지",
        like: false,
    },
    {
        productColorId: 4,
        name: "캐주얼 면바지",
        brandName: "에잇세컨즈",
        price: 30000,
        sale: false,
        priceSale: 0,
        productState: "판매중",
        productImage: null,
        category: "하의",
        categorySub: "면",
        like: false,
    },
    {
        productColorId: 5,
        name: "블루 나일론 바지",
        brandName: "아디다스",
        price: 40000,
        sale: true,
        priceSale: 20,
        productState: "판매중",
        productImage: null,
        category: "하의",
        categorySub: "나일론",
        like: false,
    },
    {
        productColorId: 6,
        name: "그레이 후드집업",
        brandName: "나이키",
        price: 60000,
        sale: false,
        priceSale: 0,
        productState: "판매중",
        productImage: null,
        category: "아우터",
        categorySub: "후드집업",
        like: false,
    },
    {
        productColorId: 7,
        name: "네이비 롱 코트",
        brandName: "버버리",
        price: 200000,
        sale: true,
        priceSale: 25,
        productState: "품절",
        productImage: null,
        category: "아우터",
        categorySub: "코트",
        like: false,
    },
    {
        productColorId: 8,
        name: "블랙 바람막이",
        brandName: "파타고니아",
        price: 80000,
        sale: false,
        priceSale: 0,
        productState: "판매중",
        productImage: null,
        category: "아우터",
        categorySub: "바람막이",
        like: false,
    },
    {
        productColorId: 9,
        name: "그린 패딩",
        brandName: "노스페이스",
        price: 150000,
        sale: true,
        priceSale: 30,
        productState: "판매중",
        productImage: null,
        category: "아우터",
        categorySub: "패딩",
        like: false,
    },
    {
        productColorId: 10,
        name: "브라운 가죽 자켓",
        brandName: "자라",
        price: 100000,
        sale: false,
        priceSale: 0,
        productState: "판매중",
        productImage: null,
        category: "아우터",
        categorySub: "자켓",
        like: false,
    }
];